2020-10-10 11:43:47,298 ERROR: Exception on /index [GET] [in c:\final project\final-course-project\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Final project\Final-course-project\app\routes.py", line 150, in index
    page, app.config['POST_PER_PAGE'], False)
KeyError: 'POST_PER_PAGE'
2020-10-10 11:43:48,598 ERROR: Exception on /explore [GET] [in c:\final project\final-course-project\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Final project\Final-course-project\app\routes.py", line 164, in explore
    page, app.config['POST_PER_PAGE'], False)
KeyError: 'POST_PER_PAGE'
2020-10-10 11:43:49,347 ERROR: Exception on /explore [GET] [in c:\final project\final-course-project\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Final project\Final-course-project\app\routes.py", line 164, in explore
    page, app.config['POST_PER_PAGE'], False)
KeyError: 'POST_PER_PAGE'
2020-10-10 11:44:27,327 INFO: Microblog startup [in C:\Final project\Final-course-project\app\__init__.py:51]
2020-10-10 11:44:28,598 ERROR: Exception on / [GET] [in c:\final project\final-course-project\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Final project\Final-course-project\app\routes.py", line 150, in index
    page, app.config['POST_PER_PAGE'], False)
KeyError: 'POST_PER_PAGE'
2020-10-10 11:44:32,069 ERROR: Exception on /user/Mark_Beltriski [GET] [in c:\final project\final-course-project\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\final project\final-course-project\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Final project\Final-course-project\app\routes.py", line 77, in user
    return render_template('user.html', user=user, posts=posts.items,
  File "c:\final project\final-course-project\venv\lib\site-packages\flask\templating.py", line 138, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "c:\final project\final-course-project\venv\lib\site-packages\jinja2\environment.py", line 930, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "c:\final project\final-course-project\venv\lib\site-packages\jinja2\environment.py", line 883, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "c:\final project\final-course-project\venv\lib\site-packages\jinja2\environment.py", line 857, in _load_template
    template = self.loader.load(self, name, globals)
  File "c:\final project\final-course-project\venv\lib\site-packages\jinja2\loaders.py", line 127, in load
    code = environment.compile(source, name, filename)
  File "c:\final project\final-course-project\venv\lib\site-packages\jinja2\environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "c:\final project\final-course-project\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\final project\final-course-project\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Final project\Final-course-project\app\templates\user.html", line 44, in template
    <a href="{{ next_url or '#' }}">
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
